In [1]:
from rdflib import Graph, RDF
from rdflib.namespace import OWL, XSD, SKOS, RDFS
import pandas as pd

In [2]:
graph = Graph()
graph.parse('../data/input/AI-RHEUM.ttl', format='ttl')

In [3]:
print(f"Graph g has {len(graph)} statements.")

Graph g has 5968 statements.

In [4]:
import itertools

class Indexer(object):
    def __init__(self,it):
        self.it = it
    
    def __iter__(self):
        return self.it
    
    def __getitem__(self,index):
        try:
            return next(itertools.islice(self.it,index,index+1))
        except TypeError:
            return list(itertools.islice(self.it,index.start,index.stop,index.step))

In [10]:

for owlClass in graph.subjects(RDF.type, OWL.Class):
    notation = Indexer(graph.objects(owlClass, SKOS.notation))
    label = Indexer(graph.objects(owlClass, SKOS.prefLabel))
    synonyms = Indexer(graph.objects(owlClass, SKOS.altLabel))
    semantic_types = Indexer(graph.objects(owlClass, RDFS.subClassOf))

In [9]:
def ret_lst(iterable):
    lst = []
    for i in iterable:
        lst.append(i[1])
    return lst

notaiton_lst = ret_lst(notation)
label_lst = ret_lst(label)
synonyms_lst = ret_lst(synonyms)
semantic_types_lst = ret_lst(semantic_types)

print(len(notaiton_lst))
print(len(label_lst))
print(len(synonyms_lst))
print(len(semantic_types_lst))

808
808
4
1323

In [7]:
# create dictionary with notation as key and label, synonyms, semantic types as values
# dic = {"id":{'label':'label', 'synonyms':['synonym1', 'synonym2', ...], 'semantic_types':['semantic_type1', 'semantic_type2', ...]}}
for idx,notaion in enumerate(notation):
    dic[str(notaion[0])] = {}
    dic[str(notaion[0])]['label'] = str(label[idx][1])
    dic[str(notaion[0])]['synonyms'] = []
    dic[str(notaion[0])]['semantic_types'] = []
    for synonym in synonyms[idx]:
        dic[str(notaion[0])]['synonyms'].append(str(synonym))
    for semantic_type in semantic_types[idx]:
        dic[str(notaion[0])]['semantic_types'].append(str(semantic_type))
        
dic

StopIteration:

In [170]:
notaiton_lst = []
label_lst = []
sunonyms_lst =[]
sem_lst =[]

for notation in graph.subject_objects(SKOS.notation):
    notaiton_lst.append(notation)

for label in graph.subject_objects(SKOS.prefLabel):
    label_lst.append(label)
    
for synonym in graph.subject_objects(SKOS.altLabel):
    sunonyms_lst.append(synonym)
    
for semt in graph.subject_objects(RDFS.subClassOf):
    sem_lst.append(semt)

#print(notaiton_lst)
#print(label_lst)
print(sunonyms_lst)
#print(sem_lst)

[(rdflib.term.URIRef('http://purl.bioontology.org/ontology/AIR/CPD'), rdflib.term.Literal('calcium pyrophosphate deposition disease', lang='en')), (rdflib.term.URIRef('http://purl.bioontology.org/ontology/AIR/DJD'), rdflib.term.Literal('primary OA', lang='en')), (rdflib.term.URIRef('http://purl.bioontology.org/ontology/AIR/JR3'), rdflib.term.Literal("Still's disease", lang='en')), (rdflib.term.URIRef('http://purl.bioontology.org/ontology/AIR/TEN'), rdflib.term.Literal('tennis elbow', lang='en'))]

In [143]:
for idx,nota in enumerate(notation):
    print(nota)
    #dic[str(notation[0])] = {"label":str(label[idx][1])}
    #dic[str(notation[0])]["semantic_types"] = [str(sem) for sem in semantic_types[idx_id]]
    #dic[str(notation[0])]["synonyms"] = [syn for syn in synonyms[idx_id]]
#     try:
#         dic[str(notation[0])]["synonyms"] = [synonym for synonym in synonyms[idx_id]]
#     except:
#         dic[str(notation[0])]["synonyms"] = synonyms[idx_id]
#     dic[str(notation[0])]["semantic_types"] = [semantic_type for semantic_type in semantic_types[idx_id]]

In [133]:
dic = []

# for i in range(len(graph)):
#     ids = next(graph.subject_objects(SKOS.notation))
#     print(ids[0])
for idd in graph.subject_objects(SKOS.notation):
    dic.append(idd)
#     for label in graph.subject_objects(SKOS.prefLabel):
#         dic[str(id[0])] = {"label":str(label[1])}
#     for synonyms in graph.subject_objects(SKOS.altLabel):
#         dic[str(id[0])]["synonyms"] = []
#         dic[str(id[0])]["synonyms"].append(str(synonyms[1]))
#     for semantic_types in graph.subject_objects(RDFS.subClassOf):
#         dic[str(id[0])]["semantic_types"] = []
#         for semantic_type in semantic_types:
#             dic[str(id[0])]["semantic_types"].append(str(semantic_type))

len(dic)

808

In [5]:
dictData = pd.DataFrame(columns=['ID', 'Label'])
for owlClass in graph.subjects(RDF.type, OWL.Class):
    for prefLabel in graph.objects(owlClass, SKOS.prefLabel):
        dictData.loc[len(dictData)] = [owlClass, prefLabel]
    for altLabel in graph.objects(owlClass, SKOS.altLabel):
        dictData.loc[len(dictData)] = [owlClass, altLabel]
        
dictData

,ID,Label
0,http://purl.bioontology.org/ontology/AIR/LBPN,Lumbar spine pain > 3 months
1,http://purl.bioontology.org/ontology/AIR/AGE,Patient age at this workup
2,http://purl.bioontology.org/ontology/AIR/BMNST,Lumbar spine pain and/or morning stiffness or ...
3,http://purl.bioontology.org/ontology/AIR/CPD,Pseudo-gout
4,http://purl.bioontology.org/ontology/AIR/CPD,calcium pyrophosphate deposition disease
...,...,...
807,http://purl.bioontology.org/ontology/STY/T085,Molecular Sequence
808,http://purl.bioontology.org/ontology/STY/T010,Vertebrate
809,http://purl.bioontology.org/ontology/STY/T016,Human
810,http://purl.bioontology.org/ontology/STY/T021,Fully Formed Anatomical Structure
811,http://purl.bioontology.org/ontology/STY/T203,Drug Delivery Device

In [6]:
dictData[dictData['ID'].astype(str)=='http://purl.bioontology.org/ontology/AIR/CPD']

Empty DataFrame
Columns: [ID, Label]
Index: []

In [156]:
dictData = pd.DataFrame(columns=['ID', 'Label'])
for elem in graph.subject_objects(SKOS.prefLabel):
    dictData.loc[len(dictData)] = [elem[0], elem[1]]
for elem in graph.subject_objects(SKOS.altLabel):
    dictData.loc[len(dictData)] = [elem[0], elem[1]]

In [8]:
dictData[dictData['ID'].astype(str)=='http://purl.bioontology.org/ontology/AIR/CPD']

Empty DataFrame
Columns: [ID, Label]
Index: []

In [9]:
dictData = pd.DataFrame(columns=['ID', 'Label'])

labelsQuery = """
SELECT DISTINCT ?id ?label
WHERE {
  { ?id a owl:Class .
  ?id skos:prefLabel ?label }
  UNION
  { ?id a owl:Class .
  ?id skos:altLabel ?label }
}
"""

qres = graph.query(labelsQuery)
for row in qres:
    dictData.loc[len(dictData)] = [row.id, row.label]

dictData

,ID,Label
0,http://purl.bioontology.org/ontology/AIR/LBPN,Lumbar spine pain > 3 months
1,http://purl.bioontology.org/ontology/AIR/AGE,Patient age at this workup
2,http://purl.bioontology.org/ontology/AIR/BMNST,Lumbar spine pain and/or morning stiffness or ...
3,http://purl.bioontology.org/ontology/AIR/CPD,Pseudo-gout
4,http://purl.bioontology.org/ontology/AIR/DXNA,None of the above
...,...,...
807,http://purl.bioontology.org/ontology/STY/T203,Drug Delivery Device
808,http://purl.bioontology.org/ontology/AIR/CPD,calcium pyrophosphate deposition disease
809,http://purl.bioontology.org/ontology/AIR/DJD,primary OA
810,http://purl.bioontology.org/ontology/AIR/JR3,Still's disease
811,http://purl.bioontology.org/ontology/AIR/TEN,tennis elbow

In [10]:
dictData[dictData['ID'].astype(str)=='http://purl.bioontology.org/ontology/AIR/CPD']

Empty DataFrame
Columns: [ID, Label]
Index: []