In [25]:
from rdflib import Graph, RDF
from rdflib.namespace import OWL, XSD, SKOS
import pandas as pd

In [13]:
graph = Graph()
graph.parse('../data/input/AI-RHEUM.ttl', format='ttl')

In [15]:
print(f"Graph g has {len(graph)} statements.")

Graph g has 5968 statements.
<generator object Graph.subjects at 0x000001B53B2FF0C8>

In [64]:
dictData = pd.DataFrame(columns=['ID', 'Label'])
for owlClass in graph.subjects(RDF.type, OWL.Class):
    for prefLabel in graph.objects(owlClass, SKOS.prefLabel):
        dictData.loc[len(dictData)] = [owlClass, prefLabel]
    for altLabel in graph.objects(owlClass, SKOS.altLabel):
        dictData.loc[len(dictData)] = [owlClass, altLabel]
        
dictData

,ID,Label
0,http://purl.bioontology.org/ontology/AIR/SPABS,"Spinal abscess, by X-ray"
1,http://purl.bioontology.org/ontology/AIR/OSTEO,Periarticular or juxta-articular osteoporosis ...
2,http://purl.bioontology.org/ontology/AIR/SACRS,Sacroiliitis
3,http://purl.bioontology.org/ontology/AIR/CSFL,CSF white blood cells with lymphocytic predomi...
4,http://purl.bioontology.org/ontology/AIR/GNDST,"Gram-negative diplococci on stain, non-synovial"
...,...,...
807,http://purl.bioontology.org/ontology/AIR/STI,Adult Still's Disease
808,http://purl.bioontology.org/ontology/AIR/PVBX,"Skin biopsy, pustular vasculitis of Behcet's d..."
809,http://purl.bioontology.org/ontology/AIR/NEPHR,Nephrotic syndrome
810,http://purl.bioontology.org/ontology/STY/T101,Patient or Disabled Group
811,http://purl.bioontology.org/ontology/STY/T033,Finding

In [65]:
dictData[dictData['ID'].astype(str)=='http://purl.bioontology.org/ontology/AIR/CPD']

,ID,Label
489,http://purl.bioontology.org/ontology/AIR/CPD,Pseudo-gout
490,http://purl.bioontology.org/ontology/AIR/CPD,calcium pyrophosphate deposition disease

In [66]:
dictData = pd.DataFrame(columns=['ID', 'Label'])
for elem in graph.subject_objects(SKOS.prefLabel):
    dictData.loc[len(dictData)] = [elem[0], elem[1]]
for elem in graph.subject_objects(SKOS.altLabel):
    dictData.loc[len(dictData)] = [elem[0], elem[1]]
    
dictData

,ID,Label
0,http://purl.bioontology.org/ontology/AIR/DXGCA,Gonococcal Arthritis
1,http://purl.bioontology.org/ontology/AIR/MFINF,Present or past infectious disease
2,http://purl.bioontology.org/ontology/AIR/DIARH,"Diarrheal illness within last 2 wks, hx"
3,http://purl.bioontology.org/ontology/AIR/LMLA,"Limitation of lumbar motion, Schober's test <5..."
4,http://purl.bioontology.org/ontology/AIR/MRMCH,"Cardiac murmur, changing"
...,...,...
807,http://purl.bioontology.org/ontology/AIR/DXBEH,Behcet's Disease
808,http://purl.bioontology.org/ontology/AIR/TEN,tennis elbow
809,http://purl.bioontology.org/ontology/AIR/CPD,calcium pyrophosphate deposition disease
810,http://purl.bioontology.org/ontology/AIR/JR3,Still's disease
811,http://purl.bioontology.org/ontology/AIR/DJD,primary OA

In [67]:
dictData[dictData['ID'].astype(str)=='http://purl.bioontology.org/ontology/AIR/CPD']

,ID,Label
381,http://purl.bioontology.org/ontology/AIR/CPD,Pseudo-gout
809,http://purl.bioontology.org/ontology/AIR/CPD,calcium pyrophosphate deposition disease

In [70]:
dictData = pd.DataFrame(columns=['ID', 'Label'])

labelsQuery = """
SELECT DISTINCT ?id ?label
WHERE {
  { ?id a owl:Class .
  ?id skos:prefLabel ?label }
  UNION
  { ?id a owl:Class .
  ?id skos:altLabel ?label }
}
"""

qres = graph.query(labelsQuery)
for row in qres:
    dictData.loc[len(dictData)] = [row.id, row.label]

dictData

,ID,Label
0,http://purl.bioontology.org/ontology/AIR/SPABS,"Spinal abscess, by X-ray"
1,http://purl.bioontology.org/ontology/AIR/OSTEO,Periarticular or juxta-articular osteoporosis ...
2,http://purl.bioontology.org/ontology/AIR/SACRS,Sacroiliitis
3,http://purl.bioontology.org/ontology/AIR/CSFL,CSF white blood cells with lymphocytic predomi...
4,http://purl.bioontology.org/ontology/AIR/GNDST,"Gram-negative diplococci on stain, non-synovial"
...,...,...
807,http://purl.bioontology.org/ontology/STY/T033,Finding
808,http://purl.bioontology.org/ontology/AIR/JR3,Still's disease
809,http://purl.bioontology.org/ontology/AIR/DJD,primary OA
810,http://purl.bioontology.org/ontology/AIR/CPD,calcium pyrophosphate deposition disease
811,http://purl.bioontology.org/ontology/AIR/TEN,tennis elbow

In [71]:
dictData[dictData['ID'].astype(str)=='http://purl.bioontology.org/ontology/AIR/CPD']

,ID,Label
487,http://purl.bioontology.org/ontology/AIR/CPD,Pseudo-gout
810,http://purl.bioontology.org/ontology/AIR/CPD,calcium pyrophosphate deposition disease